apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-x
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SEU_USUARIO/SEU_REPOSITORIO.git'
    targetRevision: HEAD
    path: charts/nestjs-app
    helm:
      valueFiles:
        - ../../applications/backend-x/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
