apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/thiagotw10/meu-lab-gitops.git'
    targetRevision: HEAD
    path: charts/nestjs-app # Reusando seu esqueleto pela quarta vez!
    helm:
      valueFiles:
        - ../../applications/pgadmin/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true