http:
  namespace: default
  port: 8000 # Porta padrão onde o Python/FastAPI costuma rodar

image:
  repository: traefik/whoami # Imagem leve do Python apenas para o pod subir no lab

resources:
  replicas: 1
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi