apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.http.namespace | default "default" }}
spec:
  replicas: {{ .Values.resources.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: nestjs
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: {{ .Values.http.port | default 3000 }}
        env:
          {{- toYaml .Values.env | nindent 12 }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
