apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.http.namespace | default "default" }}
spec:
  type: {{ .Values.http.serviceType | default "ClusterIP" }} # <-- Deixa dinâmico! Se não passar nada, assume ClusterIP
  selector:
    app: {{ .Release.Name }}
